#ifndef _CHENREG_H_
#define _CHENREG_H_

#define REGISTER_ALL_ITEMS\
/* 7:0 CH_EN */         REGISTER_ADD_ITEM(CHENREG,CH_EN, 7, 0)\
/* 15:8 CH_EN_WE */     REGISTER_ADD_ITEM(CHENREG,CH_EN_WE, 15, 8)\
/* 63:16 Undefined */

#define REGISTER_ADD_ITEM REGISTER_ADD_REG_ENUM
DEF_REG_ENUM_TYPE(CHENREG)
#undef REGISTER_ADD_ITEM

#define REGISTER_ADD_ITEM REGISTER_ADD_REG_FIELD
DEF_REG_FIELD_TYPE(CHENREG)
#undef REGISTER_ADD_ITEM

#define REGISTER_ADD_ITEM REGISTER_FORMAT_REG_BY_STRUCT
DEF_FORMAT_REG_BY_STRUCT_FUNC(CHENREG)
#undef REGISTER_ADD_ITEM

#define REGISTER_ADD_ITEM REGISTER_FORMAT_STRUCT_BY_REG
DEF_FORMAT_STRUCT_BY_REG_FUNC(CHENREG)
#undef REGISTER_ADD_ITEM

#undef REGISTER_ALL_ITEMS

typedef enum _CHENREG_CH_EN_ENUM
{
    CHENREG_CH_EN_ChannelDisable = 0,
    CHENREG_CH_EN_ChannelEnable = 1,
}CHENREG_CH_EN_ENUM;

#endif 