#ifndef _LLPX_H_
#define _LLPX_H_
#include "RegCommonDef.h"

#define REGISTER_ALL_ITEMS\
/* 1:0 LMS */           REGISTER_ADD_ITEM(LLPX,LMS, 1, 0)\
/* 31:2 LOC */          REGISTER_ADD_ITEM(LLPX,LOC, 31, 2)\
/* 63:32 Undefined */

#define REGISTER_ADD_ITEM REGISTER_ADD_REG_ENUM
DEF_REG_ENUM_TYPE(LLPX)
#undef REGISTER_ADD_ITEM

#define REGISTER_ADD_ITEM REGISTER_ADD_REG_FIELD
DEF_REG_FIELD_TYPE(LLPX)
#undef REGISTER_ADD_ITEM

#define REGISTER_ADD_ITEM REGISTER_FORMAT_REG_BY_STRUCT
DEF_FORMAT_REG_BY_STRUCT_FUNC(LLPX)
#undef REGISTER_ADD_ITEM

#define REGISTER_ADD_ITEM REGISTER_FORMAT_STRUCT_BY_REG
DEF_FORMAT_STRUCT_BY_REG_FUNC(LLPX)
#undef REGISTER_ADD_ITEM

#undef REGISTER_ALL_ITEMS

#endif 