#ifndef _SARX_H_
#define _SARX_H_

#include "RegCommonDef.h"

#define REGISTER_ALL_ITEMS\
/* 31:0 SAR */          REGISTER_ADD_ITEM(SARX,SAR, 31, 0)\
/* 63:32 Undefined */

#define REGISTER_ADD_ITEM REGISTER_ADD_REG_ENUM
DEF_REG_ENUM_TYPE(SARX)
#undef REGISTER_ADD_ITEM

#define REGISTER_ADD_ITEM REGISTER_ADD_REG_FIELD
DEF_REG_FIELD_TYPE(SARX)
#undef REGISTER_ADD_ITEM

#define REGISTER_ADD_ITEM REGISTER_FORMAT_REG_BY_STRUCT
DEF_FORMAT_REG_BY_STRUCT_FUNC(SARX)
#undef REGISTER_ADD_ITEM

#define REGISTER_ADD_ITEM REGISTER_FORMAT_STRUCT_BY_REG
DEF_FORMAT_STRUCT_BY_REG_FUNC(SARX)
#undef REGISTER_ADD_ITEM

#undef REGISTER_ALL_ITEMS

#endif